name: healthCheck.yml
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: check url health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-part11.onrender.com
          max-attempts: '4'
          retry-delay: '10s'